import { Controller } from "./core/Controller";
import { Model } from "./core/Model";
import { View } from "./core/View";
import { MacroCommand } from "./patterns/command/MacroCommand";
import { SimpleCommand } from "./patterns/command/SimpleCommand";
import { Facade } from "./patterns/facade/Facade";
import { Mediator } from "./patterns/mediator/Mediator";
import { Notification } from "./patterns/observer/Notification";
import { Notifier } from "./patterns/observer/Notifier";
import { Observer } from "./patterns/observer/Observer";
import { Proxy } from "./patterns/proxy/Proxy";
export declare const puremvc: {
    Controller: typeof Controller;
    Model: typeof Model;
    View: typeof View;
    SimpleCommand: typeof SimpleCommand;
    MacroCommand: typeof MacroCommand;
    Facade: typeof Facade;
    Mediator: typeof Mediator;
    Notification: typeof Notification;
    Notifier: typeof Notifier;
    Observer: typeof Observer;
    Proxy: typeof Proxy;
};
